version: '3'

services:
  hollander:
    build: ./
    image: hollander
    container_name: node-hollander
    # slow command for first docker-compose up:
    command: bash -c "yarn start:dev"
    #command: bash -c "yarn test:watch"
    #command: bash -c "yarn build && yarn start:prod"
    # default command
    # command: bash -c "yarn start"
    restart: unless-stopped
    ports:
      - 3000:3000 #App port
      - 9229:9229 #Debugger port
    volumes:
      - .:/app
    working_dir: '/app'
    env_file: .env
    networks:
      projetos_servicos:
        ipv4_address: 10.11.0.12

networks:
  projetos_servicos:
   external: true